### ISSUE TITLE
Blackler Needs Black Orb

### ISSUE THREAD

**Issue by Professor-Control** [Toontown-Mystery/Toontown-Mystery#1]
Apparently, Blacklers don't have the Black Orb attack.  That sounds very ironic.  I believe that she needs it because it's like a perfect match for her.
Also, you may want to fix her 'effort' animation.  It's calling from phase 5 when a SuitA effort is in phase 6.

**Comment by 2Epik4u** [comment]
this is more of a suggestion not an issue

**Comment by 2Epik4u** [comment]
i noticed that you forked ttm and put the black orb changes, if you want the black orb attack then you can make a pull request

**Comment by Professor-Control** [comment]
Very sorry, I'm new to GitHub.  Any pointers will certainly help.  Thanks.
