### ISSUE TITLE
Gag training

### ISSUE THREAD

**Issue by slappygig** [Toontown-Mystery/Toontown-Mystery#10]
Disconnected after chosing a gag track to train on ttc

**Comment by 2Epik4u** [comment]
do you have a log?

**Comment by slappygig** [comment]
yes, but ill get one

**Comment by slappygig** [comment]
[ttoff-220224_155839.log](https://github.com/Toontown-Mystery/Toontown-Mystery/files/8143556/ttoff-220224_155839.log)

**Comment by 2Epik4u** [comment]
need an AI log

**Comment by 2Epik4u** [comment]
fixed
